Removed all crafting on a stick items
game-design-driven/Create-Prepare-to-Dye pull request #588
Opened 2024-02-22 13:32 UTC by Auseawesome

Also edited recipe for the stonecutter so it can be made without any covers if you somehow lose it...

This pull request will be merged when its done, when the following checkboxes are checked and when it passes review.
[X] - tested and confirmed working
    [X] - singleplayer
    [X] - server
    [X] - all test cases
        [X] - items properly removed using removeItems()
        [X] - new recipe for stonecutter on a stick works

2024-02-22 13:40 UTC, Auseawesome commented
Don't merge this, just realised it's in the wrong script

2024-02-22 13:41 UTC, Auseawesome commented
That should now be fixed

2024-02-22 14:27 UTC, Yarden-zamir requested changes

2024-02-22 14:27 UTC, Yarden-zamir commented on kubejs/server_scripts/base/mods/craftingOnAStick.js
> +    let namespace = (string) => {
I dont like ommiting the modname as it makes it harder to refactor later. Also in this case it doesnt save you work or adds redability so i dont think it helps you anyway. I'd prefer we use the full ids and forgo this function

2024-02-23 17:31 UTC, Yarden-zamir approved these changes

2024-02-23 17:31 UTC, Auseawesome commented
Lemme remove the feature.json file quickly, this was before the last pull which fixed everything

2024-02-23 19:11 UTC, merged